Rotate vector v about x axis by angle alpha, following the righ hand rule.

In [4]:
import numpy as np

In [5]:
v = np.array([-2, 1, 2])
v

array([-2,  1,  2])

In [12]:
norm = np.linalg.vector_norm(v)
norm

np.float64(3.0)

In [6]:
alpha = np.pi / 6
alpha

0.5235987755982988

In [7]:
Rx = np.array([
    [1, 0, 0],
    [0, np.cos(alpha), -np.sin(alpha)],
    [0, np.cos(alpha), np.sin(alpha)]
])
Rx

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  0.8660254, -0.5      ],
       [ 0.       ,  0.8660254,  0.5      ]])

In [9]:
v_transformed = np.matmul(Rx, v)
v_transformed

array([-2.       , -0.1339746,  1.8660254])

In [13]:
norm_after_transformation = np.linalg.vector_norm(v_transformed)
norm_after_transformation

np.float64(2.7386127875258306)