In [ ]:
import numpy as np

In [ ]:
n = np.array([1, 1, 1])
n

array([1, 1, 1])

In [ ]:
#rotation of the xy component of the normal vector
alpha = np.arctan(n[1] / n[0])
Rxy = np.array([
    [np.cos(alpha), np.sin(alpha), 0],
    [-np.sin(alpha), np.cos(alpha), 0],
    [0, 0, 1]
])
Rxy

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [ ]:
result_vector = np.matmul(Rxy, n)
formatted_vector = [f'{x:.3f}' for x in result_vector]
print(f'Vector: {formatted_vector}')

Vector: ['1.414', '0.000', '1.000']


In [ ]:
#rotation of the rotated to xz plane vector to align with z axis
alpha = np.arctan(result_vector[0] / result_vector[2])
Rxz = np.array([
    [np.cos(alpha), 0, -np.sin(alpha)],
    [0, 1, 0],
    [np.sin(alpha), 0, np.cos(alpha)]
])
Rxz

array([[ 0.57735027,  0.        , -0.81649658],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.81649658,  0.        ,  0.57735027]])

In [ ]:
result_vector = np.matmul(Rxz, result_vector)
formatted_vector = [f'{x:.3f}' for x in result_vector]
print(f'Vector: {formatted_vector}')

Vector: ['0.000', '0.000', '1.732']


In [ ]:
#Total rotation matrix
Q = np.matmul(Rxz, Rxy)
Q

array([[ 0.40824829,  0.40824829, -0.81649658],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.57735027,  0.57735027,  0.57735027]])

In [ ]:
#reflect about xy plane
Sxy = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, -1]
])
Sxy

array([[ 1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [ ]:
#Total reflect matrix H = Q^T * Sxy * Q
H = np.matmul(np.matmul(np.transpose(Q), Sxy), Q)
H

array([[ 0.33333333, -0.66666667, -0.66666667],
       [-0.66666667,  0.33333333, -0.66666667],
       [-0.66666667, -0.66666667,  0.33333333]])

In [ ]:
result_vector = np.matmul(H, n)
formatted_vector = [f'{x:.3f}' for x in result_vector]
print(f'Vector: {formatted_vector}')

Vector: ['-1.000', '-1.000', '-1.000']
