In [ ]:
import numpy as np

In [ ]:
v = np.array([1, -2, 1])
v

array([ 1, -2,  1])

In [ ]:
n = np.array([1, 1, 2])
n

array([1, 1, 2])

In [ ]:
v_p = v - np.dot(n,v) / np.dot(n,n) * n
v_p

array([ 0.83333333, -2.16666667,  0.66666667])

In [ ]:
T = np.identity(3) - np.outer(n, n) / np.dot(n,n)
T

array([[ 0.83333333, -0.16666667, -0.33333333],
       [-0.16666667,  0.83333333, -0.33333333],
       [-0.33333333, -0.33333333,  0.33333333]])

In [ ]:
check = np.matmul(T, v)
np.allclose(check, v_p)

True

In [ ]:
det_T = np.linalg.det(T)
det_T

np.float64(7.40148683083436e-17)

The determinant is zero as expected as we reduce the volume (dimension)