In [1]:
import sys
import numpy as np

In [2]:
#line 1 = sp1 + k1*dv1, k1 is any real number
k1 = 1
sp1 = np.array([1, 1]) #starting point
dv1 = np.array([-2, 1]) #direction vector

In [3]:
#line 2 = sp2 + k2*dv2, k2 is any real number
k2 = 1
sp2 = np.array([0, 0]) #starting point, this line intersects the origin
dv2 = np.array([-2, 1]) #direction vector, equal to the first line as the lines are parallel

In [4]:
#matrix representing the linear transformation
T = np.array([
    [2, 3],
    [4, 1]
])
T

array([[2, 3],
       [4, 1]])

In [5]:
#transform line 1: T(dv1)
transformed_dv1 = np.matmul(T, dv1)
transformed_dv1

array([-1, -7])

In [6]:
#transform line 2: T(dv2)
transformed_dv2 = np.matmul(T, dv2)
transformed_dv2

array([-1, -7])

We can see that the direction vectors are the same => lines are parallel after transformation.

In [13]:
#choose points on the original line to see how the linear tranformation changes the coordinates of these points
p1 = np.array([-1, 2]) #point on on the line 1
p2 = np.array([-2, 1]) #point on on the line 2

In [14]:
#Transform point p1 on line 1
p1_transformed = np.matmul(T, p1)
p1_transformed

array([ 4, -2])

In [15]:
#Transform point p2 on line 2
p2_transformed = np.matmul(T, p2)
p2_transformed

array([-1, -7])