In [1]:
import numpy as np

A reflection about the line y = x, followed by an orthogonal projection on the y-axis, followed by 60 degrees rotation (anticlockwise).

In [2]:
#Reflectin about the the line y = x 

Sy = np.array([
    [0, 1],
    [1, 0]
])
Sy

array([[0, 1],
       [1, 0]])

In [3]:
#Orthogonal projection on y-axis
Py = np.array([
    [0, 0],
    [0, 1]
])
Py

array([[0, 0],
       [0, 1]])

In [5]:
#Rotation by 60 degrees
alpha = np.pi / 3
R = np.array([
    [np.cos(alpha), -np.sin(alpha)],
    [np.sin(alpha), np.cos(alpha)]
])
R

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

In [6]:
H = np.matmul(R, np.matmul(Py, Sy))
H

array([[-0.8660254,  0.       ],
       [ 0.5      ,  0.       ]])